import styles from '@/styles/Home.module.scss'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className ={styles.container}>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
     <h1> Wrlcome</h1>
    </div>
  )
}
